apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q6aio0ckg-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q6aio0ckg-nodejs 
  name: q6aio0ckg-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: q6aio0ckg-nodejs 
